config/routes.rb
Rails.application.routes.draw do
    root to: 'stallions#index'
    resources :stallions
    resources :broodmares
    resources :foals
end
# Prefix Verb   URI Pattern                    Controller#Action
#           root GET    /                              stallions#index
#      stallions GET    /stallions(.:format)           stallions#index
#                POST   /stallions(.:format)           stallions#create
#   new_stallion GET    /stallions/new(.:format)       stallions#new
#  edit_stallion GET    /stallions/:id/edit(.:format)  stallions#edit
#       stallion GET    /stallions/:id(.:format)       stallions#show
#                PATCH  /stallions/:id(.:format)       stallions#update
#                PUT    /stallions/:id(.:format)       stallions#update
#                DELETE /stallions/:id(.:format)       stallions#destroy
#     broodmares GET    /broodmares(.:format)          broodmares#index
#                POST   /broodmares(.:format)          broodmares#create
#  new_broodmare GET    /broodmares/new(.:format)      broodmares#new
# edit_broodmare GET    /broodmares/:id/edit(.:format) broodmares#edit
#      broodmare GET    /broodmares/:id(.:format)      broodmares#show
#                PATCH  /broodmares/:id(.:format)      broodmares#update
#                PUT    /broodmares/:id(.:format)      broodmares#update
#                DELETE /broodmares/:id(.:format)      broodmares#destroy
#          foals GET    /foals(.:format)               foals#index
#                POST   /foals(.:format)               foals#create
#       new_foal GET    /foals/new(.:format)           foals#new
#      edit_foal GET    /foals/:id/edit(.:format)      foals#edit
#           foal GET    /foals/:id(.:format)           foals#show
#                PATCH  /foals/:id(.:format)           foals#update
#                PUT    /foals/:id(.:format)           foals#update
#                DELETE /foals/:id(.:format)           foals#destroy
#   Tue Feb 28 12:53:25 ~/Dropbox/3/x/wdi/homework/201703020900L/studbook (x *)

app/models/broodmare.rb
class Broodmare < ActiveRecord::Base
  belongs_to :stallion #controversial?
  has_many :foals, dependent: :destroy #you actually wouldn't want dependent destroy! this is what would preserve a lineage in your database
end

app/controllers/broodmares_controller.rb
#############################################
# 201702221638L     EL MARTES   GIRO
## Jay those are the same sequence of characters below here
# GIRO:  CHANGED BroodmaresController to BroodmaresController
#############################################
# 201702281633L     EL MARTES   GIRO
# It's all 'borrowed' from rails conventions!
# GIRO:  BORROWED FROM GOT

class BroodmaresController < ApplicationController

  def index
    @broodmares = Broodmare.all
  end

  def show
    @broodmare = Broodmare.find(params[:id])
  end

  #############################################
  #GIRO: METHODS new AND create work as a pair
  # def new                         #GIRO:    POST   /broodmares(.:format)   broodmares#create
  #   @broodmare = Broodmare.new              #GIRO:   http://localhost:3000/broodmares/new
  #   @stallion_names = Stallion.all.map do |stallion|
  #     [stallion.name, stallion.id]               #returns this value to the map instead of orig val
  #   end
  def new
    @broodmare = Broodmare.new
    @stallion_options = Stallion.all.map do |stallion|
      [stallion.name, stallion.id]
    end
  end

  def create
    @broodmare = Broodmare.create!(broodmare_params)
    redirect_to broodmare_path(@broodmare)   #GIRO:  http://localhost:3000/broodmares/13
  end
  #GIRO: METHODS new AND create work as a pair
  #############################################




  #############################################
  #GIRO: METHODS edit AND update work as a pair
  def edit
    @broodmare = Broodmare.find(params[:id])
    # you probably want this for your form. indent it properly though!
    @stallion_options = Stallion.all.map do |stallion|
      [stallion.name, stallion.id]
    end
    
  end

  def update
    @broodmare = Broodmare.find(params[:id])
    @broodmare.update(broodmare_params)
    redirect_to broodmare_path(@broodmare)
  end
  #GIRO: METHODS edit AND update work as a pair
  #############################################


  def destroy
    @broodmare = Broodmare.find(params[:id])
    # I'd remove this comment below! kill the clutter!
    # @broodmare.destroy(broodmare_params)
    @broodmare.destroy
    redirect_to  broodmares_path(@broodmare)
  end


  #############################################
  #GIRO: THIS private FUNCTION IS SHARED THIS MUST COME AT THE END OF THIS File OTHERWISE SAYS MTD METHOD DONT EXIST
  private
  def broodmare_params
    params.require(:broodmare).permit(:name, :img_url, :color, :age, :stallion_id)
  end
  #GIRO: THIS private FUNCTION IS SHARED
  #############################################
end

app/views/broodmares/edit.html.erb
                      <!-- ########################################### -->
                      <!-- 201703032100L     EL SABADO   JAY @ FOO -->
                      <!-- ANDYF SLACKd ME DIFFERENT VERSION OF FORM HELPER -->
                      <!-- FROM  OPTIONS_FOR_SELECT -->
                      <%#f.select :stallion_id, options_for_select   (@stallion_options, :include_blank => true) %>
                      <!-- TO COLLECTION_SELECT -->
                      <%#                     f.collection_select    (:stallion_id, Stallion.all, :id, :name, prompt: true) %>
<h5>
    <div>
        <%= link_to "Visit our Stallions", stallions_path %>
    </div>
    <div>
        <%= link_to "Visit our Broodmares", broodmares_path %>
    </div>
    <div>
        <%= link_to "Visit our Foals", foals_path %>
      <br>
    </div>
</h5>

<h2>Put some kinda change on my Broodmare, NOW!</h2>

<%= form_for @broodmare, method: :put do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
<br>
    <%= f.label :age %>
    <%= f.text_field :age %>
    <br>
    <%= f.label :color %>
    <%= f.text_field :color %>
    <br>
    <%= f.label :img_url %>
    <%= f.text_field :img_url %>
    <br>
    <%= f.collection_select(:stallion_id, Stallion.all, :id, :name, prompt: true) %>  <!-- Nice work here! -->
    <%= f.submit "Change my horsey, NOW!" %>
    <% @broodmare.save %>
<%  end %>

app/views/broodmares/index.html.erb
<h1>Here are our Broodmares</h1>
<h4><%= link_to "Git me a new Broodmare", new_broodmare_path %></h4>
<br>
<% @broodmares.each do |broodmare| %>
<div class="broodmare">
  <div>  <%= link_to broodmare.id, broodmare_path(broodmare) %>
  <%= link_to broodmare.name, broodmare_path(broodmare) %>
  </div>
</div>
<% end %>
<br>
<br>
<div class="broodmare">
    <%= image_tag ("http://www.pilchuckvet.com/images/cms/Mare&Foal.jpg") %>
</div>

app/views/broodmares/new.html.erb
<h1>Enter a New Broodmare!</h1>

<%= form_for @broodmare do |f| %>
<br>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :age %>
<%= f.text_field :age %>
<br>
<%= f.label :color %>
<%= f.text_field :color %>
<br>
<%= f.label :img_url %>
<%= f.text_field :img_url %>
<br>
<!-- You could also use collection_select here, as you know :) -->
<%= f.select :stallion_id, options_for_select(@stallion_options) %>
<%= f.submit "Submit" %>
<!-- remove unused comments -->

<!--
<h2>1. Choose a Line</h2>
<form class="" action="/new_broodmare" method="get">
<select name="stallion">
<%# @stallion_names.each do |stallion| %>
<option value=stallion.name>  <%#stallion.id%> </option>
<%# end %>
</select>
<button type="submit">submit</button>
</form> -->
<!-- data_for_select = data.each { |stallion_names| [hash['name'], hash['id']] }
options_for_select(data_for_select) -->


<% end %>

app/views/broodmares/show.html.erb
<h1><%= @broodmare.name %> </h1>
<p style="align-content: center"><%= link_to "(edit)", edit_broodmare_path(@broodmare) %></p>

<h4> is in foal to </h4>

<h3><%= @broodmare.stallion.name %></h3>

<p>Age: <%= @broodmare.age %></p>
<p>Color: <%= @broodmare.color %></p>
<p>Stallion_id: <%= @broodmare.stallion_id %></p>

<div class="horsePic"> <%= image_tag (@broodmare.img_url) %> </div>