config/routes.rb
Rails.application.routes.draw do
    root to: 'stallions#index'
    resources :stallions
    resources :broodmares
    resources :foals
end
# Prefix Verb   URI Pattern                    Controller#Action
#           root GET    /                              stallions#index
#      stallions GET    /stallions(.:format)           stallions#index
#                POST   /stallions(.:format)           stallions#create
#   new_stallion GET    /stallions/new(.:format)       stallions#new
#  edit_stallion GET    /stallions/:id/edit(.:format)  stallions#edit
#       stallion GET    /stallions/:id(.:format)       stallions#show
#                PATCH  /stallions/:id(.:format)       stallions#update
#                PUT    /stallions/:id(.:format)       stallions#update
#                DELETE /stallions/:id(.:format)       stallions#destroy
#     broodmares GET    /broodmares(.:format)          broodmares#index
#                POST   /broodmares(.:format)          broodmares#create
#  new_broodmare GET    /broodmares/new(.:format)      broodmares#new
# edit_broodmare GET    /broodmares/:id/edit(.:format) broodmares#edit
#      broodmare GET    /broodmares/:id(.:format)      broodmares#show
#                PATCH  /broodmares/:id(.:format)      broodmares#update
#                PUT    /broodmares/:id(.:format)      broodmares#update
#                DELETE /broodmares/:id(.:format)      broodmares#destroy
#          foals GET    /foals(.:format)               foals#index
#                POST   /foals(.:format)               foals#create
#       new_foal GET    /foals/new(.:format)           foals#new
#      edit_foal GET    /foals/:id/edit(.:format)      foals#edit
#           foal GET    /foals/:id(.:format)           foals#show
#                PATCH  /foals/:id(.:format)           foals#update
#                PUT    /foals/:id(.:format)           foals#update
#                DELETE /foals/:id(.:format)           foals#destroy
#   Tue Feb 28 12:53:25 ~/Dropbox/3/x/wdi/homework/201703020900L/studbook (x *)

app/models/foal.rb
class Foal < ActiveRecord::Base
  belongs_to :broodmare
end

app/controllers/foals_controller.rb
#############################################
# 201702221638L     EL MARTES   GIRO
# GIRO:  CHANGED FoalsController to FoalsController
#############################################
# 201702281633L     EL MARTES   GIRO
# GIRO:  BORROWED FROM GOT

class FoalsController < ApplicationController

  def index
    @foals = Foal.all
  end

  def show
    @foal = Foal.find(params[:id])
  end

  #############################################
  #GIRO: METHODS new AND create work as a pair
  def new                         #GIRO:    POST   /foals(.:format)   foals#create
    @foal = Foal.new              #GIRO:   http://localhost:3000/foals/new
  end

  def create
    @foal = Foal.create!(foal_params)
    redirect_to foal_path(@foal)   #GIRO:  http://localhost:3000/foals/13
  end
  #GIRO: METHODS new AND create work as a pair
  #############################################



  #############################################
  #GIRO: METHODS edit AND update work as a pair
  def edit
    @foal = Foal.find(params[:id])
  end

  def update
    @foal = Foal.find(params[:id])
    @foal.update(foal_params)
    redirect_to foal_path(@foal)
  end
  #GIRO: METHODS edit AND update work as a pair
  #############################################


  def destroy
    @foal = Foal.find(params[:id])
    ## remove
    # @foal.destroy(foal_params)
    @foal.destroy
    redirect_to  foals_path(@foal)
  end


  #############################################
  #GIRO: THIS private FUNCTION IS SHARED THIS MUST COME AT THE END OF THIS File OTHERWISE SAYS MTD METHOD DONT EXIST
  private
  def foal_params
    params.require(:foal).permit(:img_url, :foal_id)
  end
  #GIRO: THIS private FUNCTION IS SHARED
  #############################################
end

app/views/foals/edit.html.erb
<h2>I just want him to be a little different ... you know, mine!</h2>

<%= form_for @foal, method: :put do |f| %>
    <%= f.label :nom_de_muerre %>
    <%= f.text_field :nom_de_muerre %>
    <br>

    <%= f.label :broodmare_id %>
    <%= f.text_field :broodmare_id %>
    <br>

    <%= f.label :color %>
    <%= f.text_field :color %>
    <br>

    <%= f.label :markings %>
    <%= f.text_field :markings %>
    <br>

    <%= f.submit "Change my horsey, NOW!" %>
<%  end %>

    <br>
    <br>

    <%= form_for @foal, method: :delete do |f| %>
    <!-- Haha -->
        <%= f.submit "My horsey went rafting with Tom Sawyer :o( delete him, i guess" %>
    <% end %>

app/views/foals/index.html.erb
<%# ############################################# %>
<%# # 201702221638L     EL MARTES   GIRO %>

<h1>Our Foals</h1>


<%= link_to "Birth a New Foal", new_foal_path %>
<br><br>

<% @foals.each do |foal| %>
<div class="foal">
<div><%= link_to foal.nom_de_muerre, foal_path(foal) %>
</div>
</div>
<% end %>
<br>
<br>
<div class="broodmare">
    <%= image_tag ("http://cdn.thehorse.com/images/cms/2016/03/pinto-foal-running-in-pasture.jpg?preset=medium") %>
</div>

app/views/foals/new.html.erb
<h1>Enter a New Foal!</h1>

<%= form_for @foal do |f| %>

<%= f.label :nom_de_muerre %>
<%= f.text_field :nom_de_muerre %>

<%= f.label :img_url %>
<%= f.text_field :img_url %>

<%= f.label :broodmare_id %>
<%= f.text_field :broodmare_id %>

<%= f.submit "Submit" %>
<% end %>

app/views/foals/show.html.erb
<h1>
    <%= @foal.nom_de_muerre %>
    <%= link_to "(edit)", edit_foal_path(@foal) %>
</h1>
<p>Color:
    <%= @foal.color %></p>
<p>Foaled:
    <%= @foal.foaling_date %></p>
<p>Broodmare:
    <%= @foal.broodmare.name %></p>
<div class="broodmare"></div>
  <div class="foal">
      <%= image_tag (@foal.img_url) %>
  </div>