config/routes.rb
Rails.application.routes.draw do
    root to: 'stallions#index'
    resources :stallions
    resources :broodmares
    resources :foals
end
# Prefix Verb   URI Pattern                    Controller#Action
#           root GET    /                              stallions#index
#      stallions GET    /stallions(.:format)           stallions#index
#                POST   /stallions(.:format)           stallions#create
#   new_stallion GET    /stallions/new(.:format)       stallions#new
#  edit_stallion GET    /stallions/:id/edit(.:format)  stallions#edit
#       stallion GET    /stallions/:id(.:format)       stallions#show
#                PATCH  /stallions/:id(.:format)       stallions#update
#                PUT    /stallions/:id(.:format)       stallions#update
#                DELETE /stallions/:id(.:format)       stallions#destroy
#     broodmares GET    /broodmares(.:format)          broodmares#index
#                POST   /broodmares(.:format)          broodmares#create
#  new_broodmare GET    /broodmares/new(.:format)      broodmares#new
# edit_broodmare GET    /broodmares/:id/edit(.:format) broodmares#edit
#      broodmare GET    /broodmares/:id(.:format)      broodmares#show
#                PATCH  /broodmares/:id(.:format)      broodmares#update
#                PUT    /broodmares/:id(.:format)      broodmares#update
#                DELETE /broodmares/:id(.:format)      broodmares#destroy
#          foals GET    /foals(.:format)               foals#index
#                POST   /foals(.:format)               foals#create
#       new_foal GET    /foals/new(.:format)           foals#new
#      edit_foal GET    /foals/:id/edit(.:format)      foals#edit
#           foal GET    /foals/:id(.:format)           foals#show
#                PATCH  /foals/:id(.:format)           foals#update
#                PUT    /foals/:id(.:format)           foals#update
#                DELETE /foals/:id(.:format)           foals#destroy
#   Tue Feb 28 12:53:25 ~/Dropbox/3/x/wdi/homework/201703020900L/studbook (x *)

app/models/stallion.rb
class Stallion < ActiveRecord::Base
  has_many :broodmares, dependent: :destroy # again i think you dont want dependent destroy here either

  # another way to to organize your entities would be to make the stallions and broodmares parallel models and the foals a true join.

  # another approach would be to use a single-table inheritance pattern:
  # http://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html
  # https://www.martinfowler.com/eaaCatalog/singleTableInheritance.html
  #http://eewang.github.io/blog/2013/03/12/how-and-when-to-use-single-table-inheritance-in-rails/
  # this last one is long-winded

  # I'm honestly not sure what the ideal approach is, but it would involve some tree-data structure representation of horses, and the question would be how best could that be represented in the db?
  # Just some food for thought!
end

app/controllers/stallions_controller.rb
#############################################
# 201702221638L     EL MARTES   GIRO
# GIRO:  CHANGED StallionsController to StallionsController
#############################################
# 201702281245L     EL MARTES   GIRO

# See comments on other controllers

class StallionsController < ApplicationController

  def index
    @stallions = Stallion.all
  end

  def show
    @stallion = Stallion.find(params[:id])
  end

  #############################################
  #GIRO: METHODS new AND create work as a pair
  def new                         #GIRO:    POST   /stallions(.:format)   stallions#create
    @stallion = Stallion.new              #GIRO:   http://localhost:3000/stallions/new
  end
  def create
    @stallion = Stallion.create!(stallion_params)
    redirect_to stallion_path(@stallion)   #GIRO:  http://localhost:3000/stallions/13
  end
  #GIRO: METHODS new AND create work as a pair
  #############################################



  #############################################
  #GIRO: METHODS edit AND update work as a pair
  def edit
    @stallion = Stallion.find(params[:id])
  end
  def update
    @stallion = Stallion.find(params[:id])
    @stallion.update(stallion_params)
    redirect_to stallion_path(@stallion)
  end
  #GIRO: METHODS edit AND update work as a pair
  #############################################


  def destroy
    @stallion = Stallion.find(params[:id])
    @stallion.destroy
    redirect_to  stallions_path(@stallion)
  end


  #############################################
  #GIRO: THIS private FUNCTION IS SHARED THIS MUST COME AT THE END OF THIS File OTHERWISE SAYS MTD METHOD DONT EXIST
  private
  def stallion_params
    params.require(:stallion).permit(:name, :img_url, :color, :age, :stud_fee, :stallion_id)
  end
  #GIRO: THIS private FUNCTION IS SHARED
  #############################################
end

app/views/stallions/edit.html.erb
<h2>Make My Stallion Really Stand Out, NOW!</h2>

<%= form_for @stallion, method: :put do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<br>
<br>
<%= f.label :age %>
<%= f.text_field :age %>
<br>
<br>
<%= f.label :color %>
<%= f.text_field :color %>
<br>
<br>
<%= f.label :img_url %>
<%= f.text_field :img_url %>
<br>
<br>
<%= f.submit "Change my horsey, NOW!" %>
<%  end %>
    <br>
    <br>
<%= form_for @stallion, method: :delete do |f| %>
    <%= f.submit "I want a new Stallion, delete this old one, NOW!" %>
<% end %>

app/views/stallions/index.html.erb
                  <%# ############################################# %>
                  <%# # 201702221638L     EL MARTES   GIRO %>

<h1>Our Stallions</h1>


<h2><%= link_to "I wants me a new Stallion", new_stallion_path %> </h2>

<% @stallions.each do |stallion| %>
    <div class="stallion">
      <div>  <%= link_to stallion.id, stallion_path(stallion) %>
      <%= link_to stallion.name, stallion_path(stallion) %>
      </div>
    </div>
<% end %>
<br>
<br>
<div class="broodmare">
    <%= image_tag ("https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Puerto_rican-Paso-Fino-Horse-chestnut.jpg/800px-Puerto_rican-Paso-Fino-Horse-chestnut.jpg") %>
</div>

app/views/stallions/new.html.erb
<h1>Arise for the New Stallion!</h1>

<%= form_for @stallion do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<br>
<br>
<%= f.label :age %>
<%= f.text_field :age %>
<br>
<br>
<%= f.label :color %>
<%= f.text_field :color %>
<br>
<br>
<%= f.label :stud_fee %>
<%= f.text_field :stud_fee %>
<br>
<br>
<%= f.label :img_url %>
<%= f.text_field :img_url %>
<br>
<br>
<%#= f.label :stallion_id %>
<%#= f.text_field :stallion_id %>

<%= f.submit "Submit" %>
<% end %>
<!--
<h2>1. Choose a Line</h2>
<form class="" action="/new_broodmare" method="get">
  <select name="stallion">
<%# @stallion_names.each do |stallion| %>
<option value=stallion.name>  <%#stallion.id%> </option>
<%# end %>
</select>
  <button type="submit">submit</button>
</form> -->
<!-- data_for_select = data.each { |stallion_names| [hash['name'], hash['id']] }
options_for_select(data_for_select) -->

app/views/stallions/show.html.erb
<h1><%= link_to @stallion.name, edit_stallion_path(@stallion) %></h1>
<p>Name:
    <%= @stallion.name %>
    <%= link_to "  (i want to change this Stallion)", edit_stallion_path(@stallion) %></p>
<p>Age:
    <%= @stallion.age %></p>
<p>Color:
    <%= @stallion.color %></p>
<p>Stallion:
    <%= @stallion.name %></p>
<div class="stallion">
    <%= image_tag (@stallion.img_url) %>
</div>